apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: stakater-delivery-mvnstorage
  namespace: delivery
spec:
  releaseName: stakater-delivery-mvnstorage
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: storage
    version: 1.0.5
  values:
    Claims:
    - name: jenkins-mvn-local-repo
      annotations:
        volume.beta.kubernetes.io/storage-class: ssd
        helm.sh/resource-policy: keep
      storage: 3Gi
      # if you speicify storageClassName then volumeName is ignored and claim is made with storageClass instead of volume
      storageClassName: "ssd"
      # volumeName: storage-volume
      labels:
        app: jenkins
      accessModes:
      - ReadWriteOnce