apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: stakater-delivery-sonarqube
  namespace: delivery
spec:
  releaseName: stakater-delivery-sonarqube
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: sonarqube
    version: 1.0.1
  values:
    image:
      tag: 7.4-community # latest at the moment
    # Without this command, custom plugins will never be copied to /extensions/plugins after being downloaded, so it's a must with this version of public chart
    command:
      - /usr/local/copy_plugins.sh
    service:
      type: ClusterIP
      labels:
        expose: "true"
      annotations:
        config.xposer.stakater.com/Domain: REPLACE_DOMAIN_NAME
        config.xposer.stakater.com/IngressNameTemplate: '{{.Service}}-{{.Namespace}}'
        config.xposer.stakater.com/IngressURLTemplate: 'sonarqube.{{.Namespace}}.{{.Domain}}'
        xposer.stakater.com/annotations: |-
          kubernetes.io/ingress.class: internal-ingress
          ingress.kubernetes.io/force-ssl-redirect: true
          exposeIngressUrl: globally
    persistence:
      enabled: true
      existingClaim: stakater-delivery-sonarqube
    database:
      type: "postgresql" 

    postgresql:
      persistence:
        storageClass: ssd
        size: 3Gi
    plugins:
      install:
        - "https://github.com/vaulttec/sonar-auth-oidc/releases/download/v1.0.4/sonar-auth-oidc-plugin-1.0.4.jar"
    sonarProperties: |
      sonar.forceAuthentication=true
      sonar.auth.oidc.enabled=true
      sonar.core.serverBaseURL=https://sonarqube.REPLACE_NAMESPACE.REPLACE_DOMAIN_NAME
      sonar.auth.oidc.providerConfiguration=REPLACE_PROVIDER_CONFIG
      sonar.auth.oidc.clientId.secured=REPLACE_CLIENT_ID
      sonar.auth.oidc.clientSecret.secured=REPLACE_CLIENT_SECRET