apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep
  labels:
    group: com.stakater.platform
    provider: stakater
    version: "0.7.2"
    app: chartmuseum
  name: stakater-delivery-chartmuseum
  namespace: delivery
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ssd
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi