apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    helm.sh/resource-policy: keep    
  labels:
    app: sonatype-nexus    
  name: stakater-delivery-nexus-data
  namespace: delivery
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 30Gi
  storageClassName: ssd
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Gi
